### ISSUE TITLE
not working?

### ISSUE THREAD

**Issue by Anankin** [shinyhut/vernacular-vnc#34]
I am trying to use this library to get screen from specific device but screens is black (width and heights are ok) or sometimes I get error (com.shinyhut.vernacular.client.exceptions.UnknownMessageTypeException: Received unexpected message type: 255
	at com.shinyhut.vernacular.client.ServerEventHandler.lambda$start$0(ServerEventHandler.java:66)
	at java.lang.Thread.run(Thread.java:748)
). 

When I use other VNC viewers everything is ok. I am not formiliar with VNC but is there different encodings or what?

**Comment by Anankin** [comment]
Device usses RFB 003.003? Is this a issue?

**Comment by Anankin** [comment]
My VNC server is (Info from Real VNC-> VNC Server default: depth 32 (32bpp) big-endian rgb mac 255,255,255 shift 0,8,16 ; requested encoding ZRLE2 ; size: 800x600)

In java application I specified pixel format: BPP_32_TRUE(32, 32, true, 255, 255, 255, 0, 8, 16).

but I am getting color missmatch. I tried with all combinatons of three color shift but without luck.

**Comment by gpowork** [comment]
@Anankin can you provide logs from your VNC server?
