### ISSUE TITLE
`client.start()` NPE in `ProtocolVersion.decode()`

### ISSUE THREAD

**Issue by liamjones** [shinyhut/vernacular-vnc#37]
Looks like `BufferedReader.readLine()` returned `null`:

```
05:51:45  Message: java.lang.NullPointerException
05:51:45  	at java.util.regex.Matcher.getTextLength(Matcher.java:1283)
05:51:45  	at java.util.regex.Matcher.reset(Matcher.java:309)
05:51:45  	at java.util.regex.Matcher.<init>(Matcher.java:229)
05:51:45  	at java.util.regex.Pattern.matcher(Pattern.java:1093)
05:51:45  	at com.shinyhut.vernacular.protocol.messages.ProtocolVersion.decode(ProtocolVersion.java:50)
05:51:45  	at com.shinyhut.vernacular.protocol.handshaking.ProtocolVersionNegotiator.negotiate(ProtocolVersionNegotiator.java:19)
05:51:45  	at com.shinyhut.vernacular.protocol.handshaking.Handshaker.handshake(Handshaker.java:22)
05:51:45  	at com.shinyhut.vernacular.client.VernacularClient.createSession(VernacularClient.java:279)
05:51:45  	at com.shinyhut.vernacular.client.VernacularClient.start(VernacularClient.java:72)
05:51:45  	at com.shinyhut.vernacular.client.VernacularClient.start(VernacularClient.java:52)
```

**Comment by floriangopp** [comment]
I see the same issue from time to time.
@liamjones could you resolve the issue?

I think that this could appear if already a client is connected to the VNC server and the server is not able to handle multiple connections.

**Comment by liamjones** [comment]
@floriangopp Nope, I haven't resolved it yet. In our case, it's been low priority - I was using it for screenshots of failed e2e tests using a Selenium docker container. We fell back to "if VNC screenshot fails, take one via Selenium" (which won't include alert dialogs, etc but is good enough for a fallback).
